# Generated by Django 2.2.16 on 2021-03-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210301_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgenteProfile',
            new_name='Agente',
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
    ]
