# Generated by Django 2.2.16 on 2021-03-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto',
            field=models.ImageField(null=True, upload_to='agentes'),
        ),
    ]
