# Generated by Django 2.2.16 on 2021-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210303_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto',
            field=models.ImageField(default='static/img/ic-11.png', upload_to='agentes'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='texto',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
