# Generated by Django 2.2.16 on 2021-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210306_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto',
            field=models.ImageField(null=True, upload_to='agentes'),
        ),
    ]
