# Generated by Django 2.2.16 on 2020-11-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('SENT', 'SENT'), ('PAIDOUT', 'PAIDOUT'), ('PENDING', 'PENDING')], default='PENDING', max_length=255, verbose_name='Estado del pedido'),
            preserve_default=False,
        ),
    ]
