# Generated by Django 2.2.16 on 2021-03-09 21:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20210307_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='posts', verbose_name='Imagen')),
                ('header', models.ImageField(upload_to='posts_headers', verbose_name='Header')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenido')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='static/img/media/sliders')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del video')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('code', models.TextField(verbose_name='Código del video')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades')),
                ('tipo_inmueble', models.CharField(blank=True, choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('tipo_operacion', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('RENTA', 'Renta'), ('EXCLUSIVA', 'Exclusiva'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('entre_calle_1', models.CharField(blank=True, max_length=100, null=True)),
                ('entre_calle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
                ('captada_por', models.CharField(blank=True, max_length=100, null=True)),
                ('construccion', models.CharField(blank=True, max_length=20, null=True)),
                ('terreno', models.CharField(blank=True, max_length=20, null=True)),
                ('frente', models.CharField(blank=True, max_length=20, null=True)),
                ('fondo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('MN', 'MN'), ('DOLARES', 'Dólares')], max_length=20, null=True)),
                ('mantenimiento_mensual', models.CharField(blank=True, max_length=20, null=True)),
                ('cubiculos', models.CharField(blank=True, max_length=20, null=True)),
                ('areas_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('banos', models.CharField(blank=True, max_length=20, null=True)),
                ('sala_juntas', models.CharField(blank=True, max_length=20, null=True)),
                ('sala_espera', models.CharField(blank=True, max_length=20, null=True)),
                ('comedor', models.CharField(blank=True, max_length=20, null=True)),
                ('cocineta', models.CharField(blank=True, max_length=20, null=True)),
                ('lineas_telefonicas', models.CharField(blank=True, max_length=20, null=True)),
                ('elevador', models.CharField(blank=True, max_length=20, null=True)),
                ('aire_acondicionado', models.CharField(blank=True, max_length=20, null=True)),
                ('bodega', models.CharField(blank=True, max_length=20, null=True)),
                ('pisos', models.CharField(blank=True, max_length=20, null=True)),
                ('canceleria', models.CharField(blank=True, max_length=20, null=True)),
                ('garage_descubierto', models.CharField(blank=True, max_length=20, null=True)),
                ('garege_cubierto', models.CharField(blank=True, max_length=20, null=True)),
                ('estilo', models.CharField(blank=True, max_length=20, null=True)),
                ('niveles', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.CharField(blank=True, max_length=20, null=True)),
                ('topografia', models.CharField(blank=True, max_length=20, null=True)),
                ('forma', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_conservacion', models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('MUY BIEN', 'Muy Bien'), ('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('instalaciones_especiales', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Agente')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Post')),
            ],
        ),
    ]
