# Generated by Django 2.2.16 on 2021-03-03 22:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20210303_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='posts', verbose_name='Imagen')),
                ('header', models.ImageField(upload_to='posts_headers', verbose_name='Header')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenido')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='static/img/media/sliders')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del video')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('code', models.TextField(verbose_name='Código del video')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades', verbose_name='Imagen')),
                ('tipo_inmueble', models.CharField(blank=True, choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('tipo_operacion', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('RENTA', 'Renta'), ('EXCLUSIVA', 'Exclusiva'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('terreno', models.CharField(blank=True, max_length=20, null=True)),
                ('banos', models.CharField(blank=True, max_length=20, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Agente')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Post')),
            ],
        ),
    ]
