# Generated by Django 2.2.16 on 2021-03-10 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Agente'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Post'),
        ),
    ]
