# Generated by Django 2.2.16 on 2021-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='prop_cita',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_colonia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_cp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_horario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_llaves',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_telefono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='aire_acondicionado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='areas_trabajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Áreas de trabajo'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='bodega',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='canceleria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='captada_por',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='clave',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cocineta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='colonia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='comedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cubiculos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cubículos'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='elevador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado_conservacion',
            field=models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('MUY BIEN', 'Muy Bien'), ('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, null=True, verbose_name='Estado de conservación'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estilo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='forma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='garage_descubierto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='garege_cubierto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='lineas_telefonicas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='moneda',
            field=models.CharField(choices=[('MN', 'MN'), ('DOLARES', 'Dólares')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='niveles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='pisos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='sala_espera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sala de espera'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='sala_juntas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sala de juntas'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='terreno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('RENTA', 'Renta'), ('EXCLUSIVA', 'Exclusiva'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='topografia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
