# Generated by Django 2.2.16 on 2020-10-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('admintotal_id', models.CharField(max_length=50, verbose_name='AdminTotal ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='offers', verbose_name='Imagen')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento')),
            ],
        ),
    ]
