# Generated by Django 2.2.16 on 2021-03-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210309_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='agente',
        ),
    ]
