# Generated by Django 2.2.16 on 2021-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210222_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_inmueble', models.CharField(blank=True, choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('tipo_operacion', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('RENTA', 'Renta'), ('EXCLUSIVA', 'Exclusiva'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('entre_calle_1', models.CharField(blank=True, max_length=100, null=True)),
                ('entre_calle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
                ('captada_por', models.CharField(blank=True, max_length=100, null=True)),
                ('construccion', models.CharField(blank=True, max_length=20, null=True)),
                ('terreno', models.CharField(blank=True, max_length=20, null=True)),
                ('frente', models.CharField(blank=True, max_length=20, null=True)),
                ('fondo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('MN', 'MN'), ('DOLARES', 'Dólares')], max_length=20, null=True)),
                ('mantenimiento_mensual', models.CharField(blank=True, max_length=20, null=True)),
                ('cubiculos', models.CharField(blank=True, max_length=20, null=True)),
                ('areas_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('banos', models.CharField(blank=True, max_length=20, null=True)),
                ('sala_juntas', models.CharField(blank=True, max_length=20, null=True)),
                ('sala_espera', models.CharField(blank=True, max_length=20, null=True)),
                ('comedor', models.CharField(blank=True, max_length=20, null=True)),
                ('cocineta', models.CharField(blank=True, max_length=20, null=True)),
                ('lineas_telefonicas', models.CharField(blank=True, max_length=20, null=True)),
                ('elevador', models.CharField(blank=True, max_length=20, null=True)),
                ('aire_acondicionado', models.CharField(blank=True, max_length=20, null=True)),
                ('bodega', models.CharField(blank=True, max_length=20, null=True)),
                ('pisos', models.CharField(blank=True, max_length=20, null=True)),
                ('canceleria', models.CharField(blank=True, max_length=20, null=True)),
                ('garage_descubierto', models.CharField(blank=True, max_length=20, null=True)),
                ('garege_cubierto', models.CharField(blank=True, max_length=20, null=True)),
                ('estilo', models.CharField(blank=True, max_length=20, null=True)),
                ('niveles', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.CharField(blank=True, max_length=20, null=True)),
                ('topografia', models.CharField(blank=True, max_length=20, null=True)),
                ('forma', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_conservacion', models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('MUY BIEN', 'Muy Bien'), ('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('instalaciones_especiales', models.CharField(blank=True, max_length=500, null=True)),
                ('prop_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_cp', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_telefono', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_cita', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_llaves', models.CharField(blank=True, max_length=120, null=True)),
                ('prop_horario', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthOffer',
        ),
    ]
