# Generated by Django 2.2.16 on 2021-03-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210308_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='propiedades')),
                ('propiedad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Propiedad')),
            ],
        ),
    ]
