# Generated by Django 2.2.16 on 2021-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20210225_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/media/propiedades', verbose_name='Imagen'),
        ),
    ]
