# Generated by Django 2.2.16 on 2020-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_monthoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='posts', verbose_name='imagen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
