# Generated by Django 2.2.16 on 2021-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_propiedad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('aPaterno', models.CharField(max_length=120)),
                ('aMaterno', models.CharField(max_length=120)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='agentes', verbose_name='Imagen')),
                ('telefono', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades', verbose_name='Imagen'),
        ),
    ]
