# Generated by Django 2.2.16 on 2021-02-25 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20210225_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='texto',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
