# Generated by Django 2.2.16 on 2020-11-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Post')),
            ],
        ),
    ]
