# Generated by Django 2.2.16 on 2021-03-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_agente_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agente',
        ),
    ]
