# Generated by Django 2.2.16 on 2021-03-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20210303_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='captada_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Captada por'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='construccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Construcción'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='C.P.'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle 1'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle 2'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fondo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='frente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frente'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='mantenimiento_mensual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matenimiento Mensual'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='moneda',
            field=models.CharField(blank=True, choices=[('MN', 'MN'), ('DOLARES', 'Dólares')], max_length=20, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='terreno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Terreno'),
        ),
    ]
