# Generated by Django 2.2.16 on 2021-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20210303_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad/Municipio'),
        ),
    ]
