# Generated by Django 2.2.16 on 2021-03-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_auto_20210304_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='inmueble',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
