# Generated by Django 2.2.16 on 2021-03-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_auto_20210304_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='inmueble',
            field=models.BooleanField(blank=True, choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], null=True),
        ),
    ]
