# Generated by Django 2.2.16 on 2021-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20210304_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='inmueble',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades', verbose_name='Imagen'),
        ),
    ]
