# Generated by Django 2.2.16 on 2021-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20210304_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='inmueble',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='IS_costumer'),
        ),
    ]
