# Generated by Django 2.2.16 on 2021-03-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20210304_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='inmueble',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
