# Generated by Django 2.2.16 on 2021-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_auto_20210304_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='boolean',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='aire_acondicionado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='areas_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='bodega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='canceleria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='captada_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Captada por'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cocineta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='comedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='construccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Construcción'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='C.P.'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cubiculos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='edad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='elevador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle 1'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle 2'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_conservacion',
            field=models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('MUY BIEN', 'Muy Bien'), ('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estilo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fondo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='forma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='frente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frente'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='garage_descubierto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='garege_cubierto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='instalaciones_especiales',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lineas_telefonicas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='mantenimiento_mensual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matenimiento Mensual'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='moneda',
            field=models.CharField(blank=True, choices=[('MN', 'MN'), ('DOLARES', 'Dólares')], max_length=20, null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='niveles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(default='Nombre de Propiedad', max_length=120),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='pisos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_cita',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_colonia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_cp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_horario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_llaves',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prop_telefono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='sala_espera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='sala_juntas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='terreno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Terreno'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(blank=True, choices=[('CASA', 'Casa con uso de suelo mixto'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('LOCAL COMERCIAL', 'Local Comercial'), ('EDIFICIO', 'Edificio'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('RENTA', 'Renta'), ('EXCLUSIVA', 'Exclusiva'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='topografia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
