# Generated by Django 2.2.16 on 2021-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_auto_20210304_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
