# Generated by Django 2.2.16 on 2021-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_propiedad_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
