# Generated by Django 2.2.16 on 2021-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20210304_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='boolean',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
